version: "3"
services:
    postgres:
        image: postgres:12-alpine
        restart: always
        volumes:
            - $HOME/docker/volumes/youtube/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
